POST http://localhost:9000/newuser
Content-Type: application/json
Authorization: Basic none none

{ 
    "name":"bernardo", 
    "pw":"1234"
}

###

GET http://localhost:9000/users/bernardo
Authorization: Basic bernardo 1234

###

GET http://localhost:9000/users/bernardo/3
Authorization: Basic bernardo 1234

###
POST http://localhost:9000/groupreg
Content-Type: application/json
Authorization: Basic bernardo 1234

{
    "identifier": "",
    "gname":"group1",
    "description":"Apartment",
    "users": ["bernardo"]
}

###
GET http://localhost:9000/groups/group11498690805s169
Authorization: Basic bernardo 1234

###
GET http://localhost:9000/groups/group1/0
Authorization: Basic tiago 1234

###

POST http://localhost:9000/newuser
Content-Type: application/json
Authorization: Basic none none

{ 
    "name":"rui", 
    "pw":"1234"
}

###

POST http://localhost:9000/newuser
Content-Type: application/json
Authorization: Basic none none

{ 
    "name":"gaga", 
    "pw":"1234"
}

###

POST http://localhost:9000/addfriend
Content-Type: application/json
Authorization: Basic rui 1234

{
    "user_id":"rui",
    "friend_id":"gaga"
}

###
POST http://localhost:9000/newtransaction
Content-Type: application/json 
Authorization: Basic bernardo 1234

{
    "usr":"bernardo",
    "grp":"group11498690805s169",
    "vals": [
        { "person":"bernardo","amount":10 }
        ],
    "msg":"transaction example",
    "ts":"1234s"
}

###
GET http://localhost:9000/transactions/36c119df7306620f786f4ff2788bb8b0585d6902c8013ff3a11551bb45995193
Authorization: Basic bernardo 1234
