flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/jbddc/hspread.git
    commit: 1a912c0f97624fe04a45eee2e27af468ae17fd5e
  extra-dep: true
- location:
    git: https://github.com/Palmik/bson-generic.git
    commit: e078def65d0dee1ea7e3205f445e47d5937851f3
  extra-dep: true
extra-deps:
- scotty-tls-0.4.1
resolver: lts-8.5
